name: dart_supervision
description: Supervision clone in Dart
version: 0.1.0
repository: https://github.com/cdeil/dart_supervision

environment:
  sdk: ">=3.0.0"

dependencies:
  path: ^1.9.1
  image: ^4.5.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
